"""add end_time in reservation model

Revision ID: 84ef69a1682d
Revises: d7c7ebcf81a2
Create Date: 2025-04-11 17:07:27.676509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ef69a1682d'
down_revision: Union[str, None] = 'd7c7ebcf81a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('end_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'end_time')
    # ### end Alembic commands ###
